[versions]
sdk-target = "36"
sdk-compile = "36"
sdk-min = "23"
agp = "8.13.2"
kotlin = "2.3.0"
versions = "0.53.0"
dokka = "2.1.0"
core-ktx = "1.17.0"
activity-compose = "1.12.2"
compose-plugin = "1.9.3"
material-icons = "1.7.3"
appcompat = "1.7.1"
coil = "3.3.0"
ktor = "3.4.0"
binaryCompatibility = "0.18.1"
publish = "0.35.0"
poko = "0.21.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dependencies = { id = "com.github.ben-manes.versions", version.ref = "versions" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
binaryCompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibility" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }

[bundles]
